name: Playwright Tests
on:
  # schedule:
  #   - cron: '0 0 1 * *' # 毎月1日に実行
  #   - cron: '0 0 1 1,4,7,10 *' # 四半期ごとの1日に実行
  workflow_dispatch: # 手動トリガーのみ
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun i
    - name: Install Playwright Browsers
      run: bunx playwright install --with-deps
    - name: Run Playwright tests
      run: bun run test
    - name: Generate Markdown Report
      run: bun run createMarkdownReport.ts
    - name: Commit and Push Report
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add report/
        git commit -m "Add test report"
        git push
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
